export const INVENTORY_TYPE_OPTIONS = [
  { value: "", label: "Inventory Type (Any)" },
  { value: "COMMERCIAL", label: "Commercial" },
  { value: "RESIDENTIAL", label: "Residential" },
];

export const FURNISHING_OPTIONS = [
  { value: "", label: "Any Furnishing" },
  { value: "UNFURNISHED", label: "Unfurnished" },
  { value: "SEMI_FURNISHED", label: "Semi Furnished" },
  { value: "FULLY_FURNISHED", label: "Fully Furnished" },
  { value: "BARE_SHELL", label: "Bare Shell" },
  { value: "WARM_SHELL", label: "Warm Shell" },
];

export const PROPERTY_REQUIREMENT_CONFIG = {
  COMMERCIAL: {
    label: "Commercial",
    subtypeLabel: "Commercial Property Type",
    subtypes: {
      OFFICE: {
        label: "Office",
        showFurnishing: true,
        fields: [
          { key: "seats", label: "Seats / Workstations", type: "number", min: 0 },
          { key: "cabins", label: "Cabins", type: "number", min: 0 },
          { key: "conferenceRooms", label: "Conference Rooms", type: "number", min: 0 },
          { key: "conferenceSeats", label: "Conference Seats", type: "number", min: 0 },
          { key: "preferredFloor", label: "Preferred Floor", type: "text" },
          { key: "receptionArea", label: "Reception Area", type: "checkbox" },
          { key: "waitingArea", label: "Waiting Area", type: "checkbox" },
          { key: "pantry", label: "Pantry", type: "checkbox" },
          { key: "cafeteria", label: "Cafeteria", type: "checkbox" },
          { key: "serverRoom", label: "Server / IT Room", type: "checkbox" },
          { key: "storageRoom", label: "Storage Room", type: "checkbox" },
          { key: "breakoutArea", label: "Breakout Area", type: "checkbox" },
          { key: "parking", label: "Parking", type: "checkbox" },
          { key: "liftAvailable", label: "Lift Available", type: "checkbox" },
          { key: "powerBackup", label: "Power Backup", type: "checkbox" },
          { key: "centralAC", label: "Central AC", type: "checkbox" },
        ],
      },
      COWORKING: {
        label: "Coworking",
        showFurnishing: true,
        fields: [
          { key: "requiredSeats", label: "Required Seats", type: "number", min: 0 },
          { key: "deskType", label: "Desk Type", type: "select", options: ["Open Desk", "Dedicated Desk", "Private Cabin"] },
          { key: "privateCabins", label: "Private Cabins", type: "number", min: 0 },
          { key: "meetingRooms", label: "Meeting Rooms", type: "number", min: 0 },
          { key: "perSeatBudget", label: "Per Seat Budget", type: "number", min: 0 },
          { key: "internetRequired", label: "Internet Required", type: "checkbox" },
          { key: "printingFacility", label: "Printing Facility", type: "checkbox" },
          { key: "reception", label: "Reception", type: "checkbox" },
          { key: "pantry", label: "Pantry", type: "checkbox" },
          { key: "parking", label: "Parking", type: "checkbox" },
          { key: "access24x7", label: "24x7 Access", type: "checkbox" },
          { key: "powerBackup", label: "Power Backup", type: "checkbox" },
        ],
      },
      MANAGED_OFFICE: {
        label: "Managed Office",
        showFurnishing: true,
        fields: [
          { key: "requiredSeats", label: "Required Seats", type: "number", min: 0 },
          { key: "cabins", label: "Cabins", type: "number", min: 0 },
          { key: "meetingRooms", label: "Meeting Rooms", type: "number", min: 0 },
          { key: "brandingRequired", label: "Branding Required", type: "checkbox" },
          { key: "itSetupRequired", label: "IT Setup Required", type: "checkbox" },
          { key: "dedicatedReception", label: "Dedicated Reception", type: "checkbox" },
          { key: "leaseDuration", label: "Lease Duration", type: "text" },
          { key: "moveInDate", label: "Move-in Date", type: "date" },
          { key: "budgetMode", label: "Budget Mode", type: "select", options: ["Per Seat", "Total"] },
          { key: "pantry", label: "Pantry", type: "checkbox" },
          { key: "parking", label: "Parking", type: "checkbox" },
          { key: "powerBackup", label: "Power Backup", type: "checkbox" },
          { key: "centralAC", label: "Central AC", type: "checkbox" },
        ],
      },
      SHOP: {
        label: "Shop",
        showFurnishing: true,
        fields: [
          { key: "preferredFloor", label: "Preferred Floor", type: "text" },
          { key: "groundFloorPreferred", label: "Ground Floor Preferred", type: "checkbox" },
          { key: "carpetArea", label: "Carpet Area", type: "number", min: 0 },
          { key: "frontage", label: "Frontage", type: "number", min: 0 },
          { key: "roadType", label: "Road Type", type: "select", options: ["Main Road", "Internal Road"] },
          { key: "cornerShop", label: "Corner Shop", type: "checkbox" },
          { key: "washroom", label: "Washroom", type: "checkbox" },
          { key: "parking", label: "Parking", type: "checkbox" },
          { key: "suitableBusinessCategory", label: "Suitable Business Category", type: "text", fullWidth: true },
          { key: "possessionDate", label: "Possession Date", type: "date" },
        ],
      },
      SHOWROOM: {
        label: "Showroom",
        showFurnishing: true,
        fields: [
          { key: "preferredFloor", label: "Preferred Floor", type: "text" },
          { key: "carpetArea", label: "Carpet Area", type: "number", min: 0 },
          { key: "frontage", label: "Frontage", type: "number", min: 0 },
          { key: "ceilingHeight", label: "Ceiling Height", type: "number", min: 0 },
          { key: "mainRoadVisibility", label: "Main Road Visibility", type: "checkbox" },
          { key: "displayArea", label: "Display Area", type: "number", min: 0 },
          { key: "parkingCapacity", label: "Parking Capacity", type: "number", min: 0 },
          { key: "brandCategory", label: "Brand Category", type: "text" },
          { key: "washroom", label: "Washroom", type: "checkbox" },
          { key: "powerLoad", label: "Power Load", type: "text" },
          { key: "possessionDate", label: "Possession Date", type: "date" },
        ],
      },
      CAFE: {
        label: "Cafe",
        showFurnishing: true,
        fields: [
          { key: "indoorArea", label: "Indoor Area", type: "number", min: 0 },
          { key: "outdoorArea", label: "Outdoor Area", type: "number", min: 0 },
          { key: "seatingCapacity", label: "Seating Capacity", type: "number", min: 0 },
          { key: "kitchenAvailable", label: "Kitchen Available", type: "checkbox" },
          { key: "exhaustProvision", label: "Exhaust Provision", type: "checkbox" },
          { key: "gasConnection", label: "Gas Connection", type: "checkbox" },
          { key: "fireNocRequired", label: "Fire NOC Required", type: "checkbox" },
          { key: "washroom", label: "Washroom", type: "checkbox" },
          { key: "parking", label: "Parking", type: "checkbox" },
          { key: "highFootfallPreferred", label: "High Footfall Preferred", type: "checkbox" },
          { key: "outdoorSeatingRequired", label: "Outdoor Seating Required", type: "checkbox" },
        ],
      },
      ROOFTOP: {
        label: "Rooftop",
        showFurnishing: true,
        fields: [
          { key: "totalRooftopArea", label: "Total Rooftop Area", type: "number", min: 0 },
          { key: "coveredArea", label: "Covered Area", type: "number", min: 0 },
          { key: "openArea", label: "Open Area", type: "number", min: 0 },
          { key: "liftAccess", label: "Lift Access", type: "checkbox" },
          { key: "washroom", label: "Washroom", type: "checkbox" },
          { key: "kitchenSetup", label: "Kitchen Setup", type: "checkbox" },
          { key: "intendedUse", label: "Intended Use", type: "select", options: ["Restaurant", "Cafe", "Event"] },
          { key: "commercialPermissionRequired", label: "Commercial Permission Required", type: "checkbox" },
          { key: "viewPreference", label: "View Preference", type: "text" },
          { key: "parking", label: "Parking", type: "checkbox" },
        ],
      },
      WAREHOUSE: {
        label: "Warehouse",
        showFurnishing: false,
        fields: [
          { key: "warehouseArea", label: "Warehouse Area", type: "number", min: 0 },
          { key: "clearHeight", label: "Clear Height", type: "number", min: 0 },
          { key: "entryGateHeight", label: "Entry Gate Height", type: "number", min: 0 },
          { key: "truckAccess", label: "Truck Access", type: "checkbox" },
          { key: "loadingUnloadingArea", label: "Loading / Unloading Area", type: "checkbox" },
          { key: "dockAvailable", label: "Dock Available", type: "checkbox" },
          { key: "powerLoad", label: "Power Load", type: "text" },
          { key: "fireSafety", label: "Fire Safety", type: "checkbox" },
          { key: "officeSpaceRequired", label: "Office Space Required", type: "checkbox" },
          { key: "washroom", label: "Washroom", type: "checkbox" },
          { key: "parking", label: "Parking", type: "checkbox" },
          { key: "roadWidth", label: "Road Width", type: "number", min: 0 },
        ],
      },
      INDUSTRIAL: {
        label: "Industrial",
        showFurnishing: false,
        fields: [
          { key: "landArea", label: "Land Area", type: "number", min: 0 },
          { key: "builtUpArea", label: "Built-up Area", type: "number", min: 0 },
          { key: "powerLoad", label: "Power Load", type: "text" },
          { key: "shedHeight", label: "Shed Height", type: "number", min: 0 },
          { key: "machinerySetupRequired", label: "Machinery Setup Required", type: "checkbox" },
          { key: "labourAccommodation", label: "Labour Accommodation", type: "checkbox" },
          { key: "truckAccess", label: "Truck Access", type: "checkbox" },
          { key: "loadingArea", label: "Loading Area", type: "checkbox" },
          { key: "fireSafety", label: "Fire Safety", type: "checkbox" },
          { key: "pollutionCategory", label: "Pollution Category", type: "text" },
          { key: "waterConnection", label: "Water Connection", type: "checkbox" },
          { key: "electricityConnection", label: "Electricity Connection", type: "checkbox" },
        ],
      },
      OTHER: {
        label: "Other",
        showFurnishing: true,
        fields: [
          { key: "customRequirementNotes", label: "Custom Requirement Notes", type: "textarea", fullWidth: true },
        ],
      },
    },
  },
  RESIDENTIAL: {
    label: "Residential",
    subtypeLabel: "Residential Property Type",
    subtypes: {
      APARTMENT: {
        label: "Apartment",
        showFurnishing: true,
        fields: [
          { key: "bhkType", label: "BHK Type", type: "select", options: ["1 BHK", "2 BHK", "3 BHK", "4 BHK", "5 BHK", "Other"] },
          { key: "preferredFloor", label: "Preferred Floor", type: "text" },
          { key: "totalFloors", label: "Total Floors", type: "number", min: 0 },
          { key: "bathrooms", label: "Bathrooms", type: "number", min: 0 },
          { key: "balconies", label: "Balconies", type: "number", min: 0 },
          { key: "facing", label: "Facing", type: "text" },
          { key: "propertyAge", label: "Property Age", type: "text" },
          { key: "gatedSociety", label: "Gated Society", type: "checkbox" },
          { key: "lift", label: "Lift", type: "checkbox" },
          { key: "security", label: "Security", type: "checkbox" },
          { key: "gym", label: "Gym", type: "checkbox" },
          { key: "swimmingPool", label: "Swimming Pool", type: "checkbox" },
          { key: "clubhouse", label: "Clubhouse", type: "checkbox" },
          { key: "parking", label: "Parking", type: "checkbox" },
          { key: "powerBackup", label: "Power Backup", type: "checkbox" },
          { key: "gasPipeline", label: "Gas Pipeline", type: "checkbox" },
          { key: "modularKitchen", label: "Modular Kitchen", type: "checkbox" },
          { key: "servantRoom", label: "Servant Room", type: "checkbox" },
          { key: "studyRoom", label: "Study Room", type: "checkbox" },
        ],
      },
      INDEPENDENT_HOUSE: { label: "Independent House", showFurnishing: true, fields: [
        { key: "bhkType", label: "BHK Type", type: "select", options: ["1 BHK", "2 BHK", "3 BHK", "4 BHK", "5 BHK", "Other"] },
        { key: "numberOfFloors", label: "Number of Floors", type: "number", min: 0 },
        { key: "plotArea", label: "Plot Area", type: "number", min: 0 },
        { key: "builtUpArea", label: "Built-up Area", type: "number", min: 0 },
        { key: "bathrooms", label: "Bathrooms", type: "number", min: 0 },
        { key: "balconies", label: "Balconies", type: "number", min: 0 },
        { key: "facing", label: "Facing", type: "text" },
        { key: "cornerProperty", label: "Corner Property", type: "checkbox" },
        { key: "privateParking", label: "Private Parking", type: "checkbox" },
        { key: "garden", label: "Garden", type: "checkbox" },
        { key: "terrace", label: "Terrace", type: "checkbox" },
        { key: "servantRoom", label: "Servant Room", type: "checkbox" },
        { key: "storageRoom", label: "Storage Room", type: "checkbox" },
        { key: "powerBackup", label: "Power Backup", type: "checkbox" },
        { key: "gasPipeline", label: "Gas Pipeline", type: "checkbox" },
        { key: "separateEntry", label: "Separate Entry", type: "checkbox" },
      ] },
      VILLA: { label: "Villa", showFurnishing: true, fields: [
        { key: "bhkType", label: "BHK Type", type: "select", options: ["2 BHK", "3 BHK", "4 BHK", "5 BHK", "Other"] },
        { key: "plotArea", label: "Plot Area", type: "number", min: 0 },
        { key: "builtUpArea", label: "Built-up Area", type: "number", min: 0 },
        { key: "numberOfFloors", label: "Number of Floors", type: "number", min: 0 },
        { key: "bathrooms", label: "Bathrooms", type: "number", min: 0 },
        { key: "balconies", label: "Balconies", type: "number", min: 0 },
        { key: "facing", label: "Facing", type: "text" },
        { key: "privateGarden", label: "Private Garden", type: "checkbox" },
        { key: "privatePool", label: "Private Pool", type: "checkbox" },
        { key: "parkingCapacity", label: "Parking Capacity", type: "number", min: 0 },
        { key: "servantRoom", label: "Servant Room", type: "checkbox" },
        { key: "studyRoom", label: "Study Room", type: "checkbox" },
        { key: "clubhouse", label: "Clubhouse", type: "checkbox" },
        { key: "security", label: "Security", type: "checkbox" },
        { key: "powerBackup", label: "Power Backup", type: "checkbox" },
        { key: "gatedCommunity", label: "Gated Community", type: "checkbox" },
      ] },
      PENTHOUSE: { label: "Penthouse", showFurnishing: true, fields: [
        { key: "bhkType", label: "BHK Type", type: "select", options: ["2 BHK", "3 BHK", "4 BHK", "5 BHK", "Other"] },
        { key: "preferredFloor", label: "Preferred Floor", type: "text" },
        { key: "terraceArea", label: "Terrace Area", type: "number", min: 0 },
        { key: "privateTerrace", label: "Private Terrace", type: "checkbox" },
        { key: "privateLift", label: "Private Lift", type: "checkbox" },
        { key: "bathrooms", label: "Bathrooms", type: "number", min: 0 },
        { key: "balconies", label: "Balconies", type: "number", min: 0 },
        { key: "servantRoom", label: "Servant Room", type: "checkbox" },
        { key: "studyRoom", label: "Study Room", type: "checkbox" },
        { key: "parking", label: "Parking", type: "checkbox" },
        { key: "powerBackup", label: "Power Backup", type: "checkbox" },
        { key: "clubhouse", label: "Clubhouse", type: "checkbox" },
        { key: "swimmingPool", label: "Swimming Pool", type: "checkbox" },
        { key: "viewPreference", label: "View Preference", type: "text" },
      ] },
      STUDIO_APARTMENT: { label: "Studio Apartment", showFurnishing: true, fields: [
        { key: "carpetArea", label: "Carpet Area", type: "number", min: 0 },
        { key: "preferredFloor", label: "Preferred Floor", type: "text" },
        { key: "attachedBathroom", label: "Attached Bathroom", type: "checkbox" },
        { key: "kitchenType", label: "Kitchen Type", type: "text" },
        { key: "balcony", label: "Balcony", type: "checkbox" },
        { key: "parking", label: "Parking", type: "checkbox" },
        { key: "lift", label: "Lift", type: "checkbox" },
        { key: "security", label: "Security", type: "checkbox" },
        { key: "powerBackup", label: "Power Backup", type: "checkbox" },
        { key: "suitableFor", label: "Suitable For", type: "select", options: ["Bachelor", "Working Professional", "Student"] },
      ] },
      BUILDER_FLOOR: { label: "Builder Floor", showFurnishing: true, fields: [
        { key: "bhkType", label: "BHK Type", type: "select", options: ["1 BHK", "2 BHK", "3 BHK", "4 BHK", "5 BHK", "Other"] },
        { key: "preferredFloor", label: "Preferred Floor", type: "text" },
        { key: "totalFloors", label: "Total Floors", type: "number", min: 0 },
        { key: "independentEntry", label: "Independent Entry", type: "checkbox" },
        { key: "parking", label: "Parking", type: "checkbox" },
        { key: "lift", label: "Lift", type: "checkbox" },
        { key: "terraceRights", label: "Terrace Rights", type: "checkbox" },
        { key: "balconies", label: "Balconies", type: "number", min: 0 },
        { key: "bathrooms", label: "Bathrooms", type: "number", min: 0 },
        { key: "facing", label: "Facing", type: "text" },
        { key: "powerBackup", label: "Power Backup", type: "checkbox" },
        { key: "propertyAge", label: "Property Age", type: "text" },
      ] },
      PLOT: { label: "Plot", showFurnishing: false, fields: [
        { key: "plotArea", label: "Plot Area", type: "number", min: 0 },
        { key: "plotLength", label: "Plot Length", type: "number", min: 0 },
        { key: "plotWidth", label: "Plot Width", type: "number", min: 0 },
        { key: "frontage", label: "Frontage", type: "number", min: 0 },
        { key: "roadWidth", label: "Road Width", type: "number", min: 0 },
        { key: "facing", label: "Facing", type: "text" },
        { key: "cornerPlot", label: "Corner Plot", type: "checkbox" },
        { key: "gatedColony", label: "Gated Colony", type: "checkbox" },
        { key: "approvedColony", label: "Approved Colony", type: "checkbox" },
        { key: "boundaryWall", label: "Boundary Wall", type: "checkbox" },
        { key: "constructionAllowed", label: "Construction Allowed", type: "checkbox" },
        { key: "ownershipType", label: "Ownership Type", type: "text" },
        { key: "suitableFor", label: "Suitable For", type: "select", options: ["Residential House", "Villa", "Investment"] },
      ] },
      FARM_HOUSE: { label: "Farm House", showFurnishing: true, fields: [
        { key: "landArea", label: "Land Area", type: "number", min: 0 },
        { key: "builtUpArea", label: "Built-up Area", type: "number", min: 0 },
        { key: "bedrooms", label: "Bedrooms", type: "number", min: 0 },
        { key: "bathrooms", label: "Bathrooms", type: "number", min: 0 },
        { key: "existingConstruction", label: "Existing Construction", type: "checkbox" },
        { key: "boundaryWall", label: "Boundary Wall", type: "checkbox" },
        { key: "waterConnection", label: "Water Connection", type: "checkbox" },
        { key: "electricityConnection", label: "Electricity Connection", type: "checkbox" },
        { key: "roadAccess", label: "Road Access", type: "checkbox" },
        { key: "gardenPlantation", label: "Garden / Plantation", type: "checkbox" },
        { key: "swimmingPool", label: "Swimming Pool", type: "checkbox" },
        { key: "servantQuarter", label: "Servant Quarter", type: "checkbox" },
        { key: "parking", label: "Parking", type: "checkbox" },
        { key: "distanceFromCity", label: "Distance From City", type: "text" },
      ] },
      PG_HOSTEL: { label: "PG / Hostel", showFurnishing: true, fields: [
        { key: "occupancyType", label: "Occupancy Type", type: "select", options: ["Male", "Female", "Co-living"] },
        { key: "sharingType", label: "Sharing Type", type: "select", options: ["Single", "Double", "Triple"] },
        { key: "numberOfBeds", label: "Number of Beds", type: "number", min: 0 },
        { key: "perBedBudget", label: "Per Bed Budget", type: "number", min: 0 },
        { key: "foodIncluded", label: "Food Included", type: "checkbox" },
        { key: "attachedWashroom", label: "Attached Washroom", type: "checkbox" },
        { key: "acRequired", label: "AC Required", type: "checkbox" },
        { key: "wifi", label: "Wi-Fi", type: "checkbox" },
        { key: "laundry", label: "Laundry", type: "checkbox" },
        { key: "powerBackup", label: "Power Backup", type: "checkbox" },
        { key: "security", label: "Security", type: "checkbox" },
        { key: "parking", label: "Parking", type: "checkbox" },
        { key: "moveInDate", label: "Move-in Date", type: "date" },
      ] },
      OTHER: { label: "Other", showFurnishing: true, fields: [
        { key: "customRequirementNotes", label: "Custom Requirement Notes", type: "textarea", fullWidth: true },
      ] },
    },
  },
};

export const getPropertySubtypeOptions = (inventoryType = "") =>
  Object.entries(PROPERTY_REQUIREMENT_CONFIG[String(inventoryType).toUpperCase()]?.subtypes || {})
    .map(([value, config]) => ({ value, label: config.label }));

export const getPropertySubtypeConfig = (inventoryType = "", propertySubtype = "") =>
  PROPERTY_REQUIREMENT_CONFIG[String(inventoryType).toUpperCase()]?.subtypes?.[
    String(propertySubtype).toUpperCase()
  ] || null;

export const getPropertySubtypeLabel = (inventoryType = "", propertySubtype = "") =>
  getPropertySubtypeConfig(inventoryType, propertySubtype)?.label || "";
