export const QUICK_FILTER_KEYS = {
  NEEDS_FOLLOW_UP_TODAY: "NEEDS_FOLLOW_UP_TODAY",
  OVERDUE_FOLLOW_UPS: "OVERDUE_FOLLOW_UPS",
  UNASSIGNED_LEADS: "UNASSIGNED_LEADS",
  NEW_THIS_WEEK: "NEW_THIS_WEEK",
};
