import { createElement, useCallback, useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import { AlertCircle, BriefcaseBusiness, Building2, CheckCircle2, ChevronLeft, ChevronRight, Download, FileText, Heart, Image as ImageIcon, KeyRound, Loader, Map, MapPin, Maximize2, Ruler, Share2, Sparkles, UsersRound, X } from "lucide-react";
import { getSharedInventory } from "../../services/publicInventoryService";
import "./SharedInventoryView.css";

const price = (value) => value !== null && value !== undefined && value !== "" && Number.isFinite(Number(value)) ? `₹${Number(value).toLocaleString("en-IN")}` : "Price on request";
const label = (value) => String(value || "").trim().toLowerCase().replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()) || null;
const shown = (value) => value !== null && value !== undefined && value !== "";
const area = (value, unit) => shown(value) && Number.isFinite(Number(value)) ? `${Number(value).toLocaleString("en-IN")} ${String(unit).toUpperCase() === "SQ_M" ? "sq m" : "sq ft"}` : null;

const Row = ({ name, value }) => shown(value) ? <div className="shared-detail-row"><span className="text-xs text-slate-500">{name}</span><span className="break-words text-xs font-semibold text-slate-800">{value}</span></div> : null;
const Card = ({ icon, title, children, className = "" }) => <section className={`shared-section-card ${className}`}><div className="shared-section-heading">{createElement(icon, { size: 17 })}<h2 className="font-serif font-bold">{title}</h2></div><div className="shared-section-body">{children}</div></section>;
const Metric = ({ icon, name, value, alert }) => shown(value) ? <div className="shared-metric"><span className="shared-metric-icon">{createElement(icon, { size: 20 })}</span><span><small className="block text-slate-500">{name}</small><b className={alert ? "text-red-600" : "text-slate-800"}>{value}</b></span></div> : null;

const Lightbox = ({ images, index, close, prev, next }) => {
  useEffect(() => { const key = (e) => { if (e.key === "Escape") close(); if (e.key === "ArrowLeft") prev(); if (e.key === "ArrowRight") next(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [close, next, prev]);
  return (
    <div className="shared-lightbox" role="dialog" aria-modal="true" aria-label="Property photos" onClick={close}>
      <button type="button" autoFocus aria-label="Close photo viewer" onClick={(e) => { e.stopPropagation(); close(); }} className="shared-lightbox-close"><X size={26} /></button>
      {images.length > 1 ? <>
        <button type="button" aria-label="Previous photo" onClick={(e) => { e.stopPropagation(); prev(); }} className="shared-lightbox-prev"><ChevronLeft size={28} /></button>
        <button type="button" aria-label="Next photo" onClick={(e) => { e.stopPropagation(); next(); }} className="shared-lightbox-next"><ChevronRight size={28} /></button>
      </> : null}
      <img src={images[index]} alt={`Property photo ${index + 1}`} onClick={(e) => e.stopPropagation()} />
    </div>
  );
};

export default function SharedInventoryView() {
  const { shareToken } = useParams();
  const [inventory, setInventory] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [imageIndex, setImageIndex] = useState(0);
  const [lightbox, setLightbox] = useState(false);
  const [copied, setCopied] = useState(false);
  const [saved, setSaved] = useState(false);

  const load = useCallback(async () => { try { setLoading(true); setError(""); const data = await getSharedInventory(shareToken); if (!data) throw new Error("Property not found"); setInventory(data); } catch (e) { setError(e?.response?.status === 410 ? "This share link has expired. Please request a new link." : e?.response?.data?.message || e.message || "Unable to load property"); } finally { setLoading(false); } }, [shareToken]);
  useEffect(() => { if (shareToken) load(); else { setError("This share link is invalid."); setLoading(false); } }, [load, shareToken]);

  const images = useMemo(() => Array.isArray(inventory?.images) ? inventory.images.filter(Boolean) : [], [inventory?.images]);
  const docs = useMemo(() => Array.isArray(inventory?.documents) ? inventory.documents.filter(Boolean) : [], [inventory?.documents]);
  const plans = useMemo(() => Array.isArray(inventory?.floorPlans) ? inventory.floorPlans.filter(Boolean) : [], [inventory?.floorPlans]);
  const commercial = inventory?.commercialDetails || {}, layout = commercial.officeLayout || {}, building = commercial.buildingDetails || {}, availability = commercial.availability || {}, amenities = commercial.amenities || {};
  const residential = inventory?.residentialDetails || {};
  const isCommercial = String(inventory?.inventoryType).toUpperCase() === "COMMERCIAL";
  const safeIndex = Math.min(imageIndex, Math.max(images.length - 1, 0));
  const prev = useCallback(() => setImageIndex((i) => i <= 0 ? images.length - 1 : i - 1), [images.length]);
  const next = useCallback(() => setImageIndex((i) => i >= images.length - 1 ? 0 : i + 1), [images.length]);
  const title = inventory?.title || "Property Details";
  const address = [inventory?.location, inventory?.city, inventory?.area, inventory?.pincode].filter(Boolean).filter((v, i, a) => a.indexOf(v) === i).join(", ");
  const transaction = label(inventory?.type) || "Sale";
  const share = async () => { try { if (navigator.share) await navigator.share({ title, url: location.href }); else await navigator.clipboard.writeText(location.href); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { /* cancelled */ } };
  const amenityList = [["Reception Area", layout.receptionArea], ["Waiting Area", layout.waitingArea], ["Pantry", amenities.pantry], ["Cafeteria", amenities.cafeteria], ["Server Room", amenities.serverRoom], ["Power Backup", amenities.powerBackup], ["Central AC", amenities.centralAC], ["Lift", amenities.liftAvailable], ["Security", residential?.amenities?.security], ["Gym", residential?.amenities?.gym], ["Storage Room", amenities.storageRoom], ["Breakout Area", amenities.breakoutArea], ["Fire Safety", building.fireSafety], ["Modular Kitchen", residential?.amenities?.modularKitchen], ["Lift", residential?.amenities?.lift], ["Power Backup", residential?.amenities?.powerBackup], ["Swimming Pool", residential?.amenities?.swimmingPool], ["Clubhouse", residential?.amenities?.clubhouse], ["Electricity Backup", residential?.utilities?.electricityBackup], ["Gas Pipeline", residential?.utilities?.gasPipeline]].filter(([, active]) => active);

  if (loading) return <div className="grid min-h-screen place-items-center bg-slate-50 text-slate-500"><div><Loader className="mx-auto mb-3 animate-spin text-emerald-700" />Loading property details...</div></div>;
  if (error) return <div className="grid min-h-screen place-items-center bg-slate-50 px-4 text-center"><div><AlertCircle className="mx-auto mb-3 text-red-500" size={42} /><h1 className="text-2xl font-bold">Link unavailable</h1><p className="mt-2 text-slate-500">{error}</p></div></div>;

  return <div className="shared-property-page">
    {lightbox && images.length ? <Lightbox images={images} index={safeIndex} close={() => setLightbox(false)} prev={prev} next={next} /> : null}
    <header className="shared-header"><div className="shared-header-inner"><div className="flex items-center gap-3"><span className="shared-brand-icon"><Building2 /></span><div><b className="text-lg">Office on Rent</b><small className="block text-[9px] font-bold uppercase tracking-widest text-emerald-700">Property Showcase</small></div></div><button type="button" onClick={share} className="flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><Share2 size={16} />{copied ? "Link copied" : "Share"}</button></div></header>
    <section className="shared-hero"><div className="shared-hero-pattern" /><div className="shared-hero-inner"><p className="mb-3 text-xs text-white/65">Properties&nbsp; / &nbsp;Property Details</p><h1 className="text-2xl font-extrabold sm:text-4xl">{title}</h1>{address ? <p className="mt-2 flex gap-1.5 text-sm text-white/85"><MapPin size={16} />{address}</p> : null}<div className="mt-4 flex flex-wrap gap-2"><span className={`shared-status ${String(inventory?.status).toLowerCase() === "available" ? "is-available" : ""}`}><CheckCircle2 size={14} />{label(inventory?.status) || "Available"}</span><span className="shared-hero-badge">{transaction}</span><span className="shared-hero-badge">{label(inventory?.inventoryType)}</span></div></div></section>
    <main className="shared-content">
      <div className="shared-overview">
        <section className="shared-gallery"><div className="flex gap-3"><div className="shared-gallery-stage">{images.length ? <img src={images[safeIndex]} alt={`Property ${safeIndex + 1}`} className="h-full w-full object-contain" /> : <div className="grid h-full place-items-center text-slate-300"><ImageIcon size={48} /></div>}{images.length ? <><span className="shared-photo-counter">{safeIndex + 1}/{images.length}</span><button type="button" onClick={() => setLightbox(true)} aria-label="Enlarge photo" className="shared-photo-expand"><Maximize2 size={16} /></button></> : null}{images.length > 1 ? <><button type="button" onClick={prev} aria-label="Previous photo" className="shared-photo-prev"><ChevronLeft /></button><button type="button" onClick={next} aria-label="Next photo" className="shared-photo-next"><ChevronRight /></button></> : null}</div>{images.length > 1 ? <div className="shared-thumbnails">{images.map((url, i) => <button type="button" key={url + i} onClick={() => setImageIndex(i)} aria-label={`Show photo ${i + 1}`} aria-pressed={i === safeIndex} className={`shared-thumbnail ${i === safeIndex ? "is-active" : ""}`}><img src={url} alt="Thumbnail" className="h-full w-full object-cover" /></button>)}</div> : null}</div></section>
        <aside className="shared-summary"><div className="shared-price"><div><small className="font-bold uppercase tracking-widest text-emerald-700">{transaction === "Rent" ? "Monthly Rent" : "Asking Price"}</small><p className="text-3xl font-extrabold text-emerald-900">{price(transaction === "Rent" ? inventory?.rent ?? inventory?.price : inventory?.price)}</p></div>{area(inventory?.carpetArea ?? inventory?.totalArea, inventory?.areaUnit) ? <div className="border-l border-emerald-200 pl-5"><Ruler className="text-emerald-700" /><small>Carpet Area</small><b className="block">{area(inventory?.carpetArea ?? inventory?.totalArea, inventory?.areaUnit)}</b></div> : null}</div><div className="shared-summary-rows"><div><Row name="Project" value={inventory?.projectName} /><Row name="Tower / Block" value={inventory?.towerName} /><Row name="Unit" value={inventory?.unitNumber} /><Row name="Property ID" value={inventory?.propertyId} /><Row name="Building" value={inventory?.buildingName} /><Row name="Floor" value={inventory?.floorNumber} /></div><div><Row name="Property Type" value={label(inventory?.inventoryType)} /><Row name={isCommercial ? "Commercial Type" : "Residential Type"} value={label(isCommercial ? commercial.officeType : residential.propertyType)} /><Row name="Furnishing" value={label(inventory?.furnishingStatus)} /><Row name="Built-up Area" value={area(inventory?.builtUpArea, inventory?.areaUnit)} /><Row name="Total Floors" value={inventory?.totalFloors ?? building.totalFloors} /><Row name="Maintenance" value={shown(inventory?.maintenanceCharges) ? price(inventory.maintenanceCharges) : null} /></div></div><div className="shared-actions"><button type="button" onClick={() => window.print()} className="flex items-center justify-center gap-2 rounded-xl border border-emerald-700 py-3 text-xs font-bold text-emerald-800"><Download size={15} />Print / Save PDF</button><button type="button" onClick={share} className="flex items-center justify-center gap-2 rounded-xl border border-emerald-700 text-xs font-bold text-emerald-800"><Share2 size={15} />Share</button><button type="button" onClick={() => setSaved((value) => !value)} aria-pressed={saved} className="shared-save" aria-label={saved ? "Unsave property" : "Save property"}><Heart size={18} fill={saved ? "currentColor" : "none"} /></button></div></aside>
      </div>
      <div className="shared-metrics"><Metric icon={Building2} name="Property Type" value={label(inventory?.inventoryType)} /><Metric icon={BriefcaseBusiness} name={isCommercial ? "Office Type" : "Home Type"} value={label(isCommercial ? commercial.officeType : residential.propertyType)} />{isCommercial ? <><Metric icon={UsersRound} name="Cabins" value={layout.totalCabins} /><Metric icon={UsersRound} name="Workstations" value={layout.workstations ?? layout.seats} /><Metric icon={UsersRound} name="Conference Rooms" value={layout.conferenceRooms} /><Metric icon={KeyRound} name="Ready to Move" value={shown(availability.readyToMove) ? availability.readyToMove ? "Yes" : "No" : null} alert={availability.readyToMove === false} /></> : null}</div>
      <div className="shared-details"><Card icon={Building2} title="Property Information"><Row name="Project" value={inventory?.projectName} /><Row name="Tower / Block" value={inventory?.towerName} /><Row name="Unit" value={inventory?.unitNumber} /><Row name="Property ID" value={inventory?.propertyId} /><Row name="Category" value={label(inventory?.category)} /><Row name="Furnishing" value={label(inventory?.furnishingStatus)} /><Row name="Floor" value={inventory?.floorNumber} /><Row name="Total Floors" value={inventory?.totalFloors} /></Card><Card icon={BriefcaseBusiness} title={isCommercial ? "Commercial Details" : "Residential Details"}>{isCommercial ? <><Row name="Commercial Property Type" value={label(commercial.officeType)} /><Row name="Cabins" value={layout.totalCabins} /><Row name="Cabin Seats" value={layout.cabinSeats} /><Row name="Workstations" value={layout.workstations ?? layout.seats} /><Row name="Conference Rooms" value={layout.conferenceRooms} /><Row name="Conference Seats" value={layout.conferenceSeats} /><Row name="Parking Type" value={label(building.parkingType)} /><Row name="Parking Slots" value={building.parkingSlots} /></> : <><Row name="Property Type" value={label(residential.propertyType)} /><Row name="BHK" value={label(residential.bhkType)} /><Row name="Bedrooms" value={residential.bedrooms} /><Row name="Bathrooms" value={residential.bathrooms} /><Row name="Parking Slots" value={residential.parking} /></>}</Card><div className="space-y-4">{amenityList.length ? <Card icon={Sparkles} title="Amenities"><div className="flex flex-wrap gap-2 py-2">{amenityList.map(([name]) => <span key={name} className="shared-amenity"><CheckCircle2 size={13} />{name}</span>)}</div></Card> : null}{docs.length || plans.length || inventory?.videoTours?.length ? <Card icon={FileText} title="Files & Media"><div className="grid gap-2 py-2">{[...docs.map((url, i) => [url, `Document ${i + 1}`]), ...plans.map((url, i) => [url, `Floor Plan ${i + 1}`]), ...(inventory?.videoTours || []).map((url, i) => [url, `Video Tour ${i + 1}`])].map(([url, name]) => <a key={url + name} href={url} target="_blank" rel="noreferrer" className="shared-file"><span className="flex gap-2"><FileText size={16} />{name}</span><Download size={15} /></a>)}</div></Card> : null}</div></div>
      {inventory?.siteLocation?.lat != null && inventory?.siteLocation?.lng != null ? <Card icon={Map} title="Location"><div className="shared-location"><div className="flex gap-3 rounded-xl bg-slate-50 p-4"><MapPin className="shrink-0 text-emerald-700" /><div><b className="text-sm">{address || "Property location"}</b><p className="mt-1 text-xs text-slate-500">Explore the location and nearby connectivity.</p></div></div><div className="shared-map"><iframe title="Property location" width="100%" height="100%" style={{ border: 0 }} src={`https://www.google.com/maps?q=${inventory.siteLocation.lat},${inventory.siteLocation.lng}&z=15&output=embed`} allowFullScreen /></div></div></Card> : null}
      <footer className="py-6 text-center text-xs text-slate-400">Shared securely via <b className="text-slate-600">Office on Rent</b></footer>
    </main>
  </div>;
}
